# Created by: iblis <iblis@hs.ntnu.edu.tw>

PORTNAME=	c-blosc
PORTVERSION=	1.12.0
DISTVERSIONPREFIX=	v
CATEGORIES=	archivers devel
MASTER_SITES=	GH

MAINTAINER=	iblis@hs.ntnu.edu.tw
COMMENT=	Blocking, shuffling and loss-less compression library

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSES/BLOSC.txt

USES=		cmake

USE_GITHUB=	yes
GH_ACCOUNT=	Blosc
GH_PROJECT=	c-blosc

TEST_TARGET=	test


.include <bsd.port.mk>
